const list = [
  {
    id: 1,
    title: "HP Laptop",
    description: "HP 15s, AMD Ryzen 5 5500U, 15.6 inch(39.6cm)",
    price: 44490,
    img: "https://m.media-amazon.com/images/I/81TdQekShgL._SL1500_.jpg",
    amount: 1,
  },
  {
    id: 2,
    title: "Lenovo IdeaPad",
    description: "11th Gen Intel Core i3 15.6 FHD Thin & Light Laptop",
    price: 37380,
    img: "https://m.media-amazon.com/images/I/513w75K0ffL.jpg",
    amount: 1,
  },
  {
    id: 3,
    title: "Mouse",
    description: "Logitech B170 Wireless Mouse, 2.4 GHz with USB Nano Receiver, Optical Tracking",
    price: 595,
    img: "https://m.media-amazon.com/images/I/516LU0H963L._SL1500_.jpg",
    amount: 1,
  },
  {
    id: 4,
    title: "Washing Machiene",
    description: "LG 7 Kg 5 Star Semi-Automatic Top Loading Washing Machine",
    price: 11990,
    img: "https://m.media-amazon.com/images/I/61xtcXJfYaL._SL1500_.jpg",
    amount: 1,
  },
  {
    id: 5,
    title: "Heels",
    description: "Denill Comfortable Fashion Sandal Collection For Women And Girls",
    price: 500,
    img: "https://m.media-amazon.com/images/I/61XX59hS-+L._UL1500_.jpg",
    amount: 1,
  },
  {
    id: 6,
    title: "Rasgulla",
    description: "Gits Open & Eat Rasgulla Tin, 16 Pieces per Can",
    price: 172,
    img: "https://m.media-amazon.com/images/I/81GgFiz-FjL._SL1500_.jpg",
    amount: 1,
  },
  {
    id: 7,
    title: "Perfume",
    description: "The Man Company Tranquil Perfume for Men | EDP for Him",
    price: 433,
    img: "https://m.media-amazon.com/images/I/61XuHTF2eTL._SL1000_.jpg",
    amount: 1,
  },
  {
    id: 8,
    title: "Face Wash",
    description: "Garnier Men Tubro Bright Anti-Dark Cells Fairness Face Wash",
    price: 189,
    img: "https://m.media-amazon.com/images/I/41QHfCK+D6L._SL1073_.jpg",
    amount: 1,
  },
  {
    id: 9,
    title: "Blossom Moral Story Book for Kids ",
    description: "by Content Team at Target Publications",
    price: 80,
    img: "https://m.media-amazon.com/images/I/7122h3jWvEL._AC_UY327_FMwebp_QL65_.jpg",
    amount: 1,
  },
  {
    id: 10,
    title: "Dresses",
    description: "Lymio Dresses for Women || Western Dresses for Women",
    price: 600,
    img: "https://m.media-amazon.com/images/I/71d5fPA2QuL._UY679_.jpg",
    amount: 1,
  },
  {
    id: 11,
    title: "Watch",
    description: "Alexandre Christie AC 3030 MCL Chronograph for Men – Black",
    price: 26995,
    img: "https://m.media-amazon.com/images/I/61SXFFRwBRL._UL1200_.jpg",
    amount: 1,
  },
  {
    id: 12,
    title: "Bags",
    description: "American Tourister VALEX BLACK LAPTOP BACKPACK 28 Ltrs,Volume, LAPTOP COMPARTMENT",
    price: 1199,
    img: "https://m.media-amazon.com/images/I/913C9PlkyfL._UL1500_.jpg",
    amount: 1,
  },
];

export default list;
